### ISSUE TITLE
Could you please host a demo?

### ISSUE THREAD

**Issue by Gaurav0** [ScottLNorvell/ember-tetris-addon#2]
You can use github pages or any other free hosting provider for static sites.

**Comment by ScottLNorvell** [comment]
Thanks for the suggestion! I'm working on documentation which requires one to refactor a bit and then I'll host a proper demo. 

Stay Tuned!

**Comment by robbyoconnor** [comment]
:+1:

**Comment by ScottLNorvell** [comment]
Closed! See demo link on readme.
